# Generated by Django 2.2.8 on 2020-07-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('cat1', 'cat1')], default='noCat', max_length=255),
        ),
    ]
