# Generated by Django 2.2.8 on 2020-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('cat1', 'cat1'), ('cat2', 'cat2')], default='noCat', max_length=255),
        ),
    ]
