# Generated by Django 2.2.8 on 2020-08-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200806_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='tel',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
