# Generated by Django 2.2.8 on 2020-08-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200807_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.ManyToManyField(blank=True, to='core.ItemPrice'),
        ),
    ]
