# Generated by Django 2.2.8 on 2020-08-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shopcart_model'),
        ('core', '0030_auto_20200808_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ItemImages',
            new_name='ProductImages',
        ),
        migrations.RenameModel(
            old_name='ItemPrice',
            new_name='ProductType',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='item',
            new_name='product',
        ),
    ]
