# Generated by Django 2.2.8 on 2020-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200808_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='model',
        ),
    ]
