# Generated by Django 2.2.8 on 2020-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200808_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=5),
        ),
    ]
