# Generated by Django 2.2.8 on 2020-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_producttype_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='size',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
