# Generated by Django 2.2.8 on 2020-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200809_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ManyToManyField(default='white', to='core.ProductType'),
        ),
    ]
