# Generated by Django 2.2.8 on 2020-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200814_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='small',
            field=models.BooleanField(default=True),
        ),
    ]
