# Generated by Django 2.2.8 on 2020-08-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200815_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='qr',
        ),
        migrations.AddField(
            model_name='product',
            name='qr',
            field=models.BooleanField(default=False),
        ),
    ]
