# Generated by Django 2.2.8 on 2020-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_product_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='qr',
            field=models.BooleanField(default=False),
        ),
    ]
