# Generated by Django 2.2.8 on 2020-08-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_producttype_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='qr',
        ),
    ]
