# Generated by Django 2.2.8 on 2020-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_producttype_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='model',
            field=models.CharField(choices=[('single', 'single'), ('set', 'set'), ('family', 'family')], default='single', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
