# Generated by Django 2.2.8 on 2020-08-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200816_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='size',
        ),
    ]
