# Generated by Django 2.2.8 on 2020-08-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shopcart_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='model',
        ),
    ]
