# Generated by Django 2.2.8 on 2020-08-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200808_1810'),
        ('order', '0004_shopcart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='productType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProductType'),
        ),
    ]
