# Generated by Django 2.2.8 on 2020-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shopcart_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='productType',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='model',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
