# Generated by Django 2.2.8 on 2020-08-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200808_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
