# Generated by Django 2.2.8 on 2020-08-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200808_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
