# Generated by Django 2.2.8 on 2020-08-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_shopcart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
