# Generated by Django 2.2.8 on 2020-08-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='products',
            new_name='user',
        ),
    ]
