# Generated by Django 2.2.8 on 2020-08-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200811_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
