# Generated by Django 2.2.8 on 2020-08-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
