# Generated by Django 2.2.8 on 2020-08-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20200813_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='order.ShopCart'),
        ),
    ]
