# Generated by Django 2.2.8 on 2020-08-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_shopcart_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='qr',
            field=models.BooleanField(default=False),
        ),
    ]
