# Generated by Django 2.2.8 on 2020-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20200815_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='qr',
            field=models.BooleanField(),
        ),
    ]
