# Generated by Django 2.2.8 on 2020-09-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_auto_20200901_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='criticism',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='انتقاد'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='familiar',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='نحوه آشنایی'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(max_length=500, verbose_name='نام گیرنده'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.CharField(max_length=4000, verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tel',
            field=models.CharField(max_length=17, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='zip_code',
            field=models.CharField(max_length=500, verbose_name='کد پستی'),
        ),
    ]
